# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: Professor Charles Francis Xavier
  admin_email: xavier@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 2fc4927af5dd0969e16754bfefc44d2bf45b975a1cfafb333a4871c2c79f2d0f3e16e33a54464f72f3bb8163cfbd1a2567f22871a5854201c343ca3580f62246

test:
  admin_name: Professor Charles Francis Xavier
  admin_email: xavier@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 4c7a6f1744cc9f388d3be1e6d00debef7a09fefe370926b0d1faf85b29c712729c8b04d505ae3d08a4bf60ab3d0acad464cb5d635b97add99a92b9739629f200

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
